// Code generated by go generate. DO NOT EDIT.

package codes

const (
	// OK OK is returned on success.
	OK Code = 0

	// Unknown 未知错误
	Unknown Code = 1000

	// NotImplemented 方法未实现
	NotImplemented Code = 1001

	// Internal 内部错误
	Internal Code = 1002

	// Unavailable 服务不可用
	Unavailable Code = 1003

	// InvalidArgument 非法的参数
	InvalidArgument Code = 1004

	// OutOfRange 参数超出范围
	OutOfRange Code = 1005

	// InvalidRequest 非法的 Request 消息
	InvalidRequest Code = 1006

	// Unauthenticated 未认证
	Unauthenticated Code = 1007

	// PermissionDenied 拒绝访问
	PermissionDenied Code = 1008

	// NotFound 资源未找到
	NotFound Code = 1009

	// AlreadyExists 资源已存在
	AlreadyExists Code = 1010

	// Canceled 已取消
	Canceled Code = 1011

	// DataLoss 数据丢失
	DataLoss Code = 1012

	// DataAccessFailed 数据访问失败
	DataAccessFailed Code = 1013

	// InvalidOperation 非法的操作
	InvalidOperation Code = 1014

	// CustomizedExample 一个示例自定义错误
	CustomizedExample Code = 9000

	// InvokeAlgorithmServerFailure 调用算法服务器失败
	InvokeAlgorithmServerFailure Code = 9001
)

var codeToMsg = map[Code]string{
	OK:                           "ok",
	Unknown:                      "unknown error",
	NotImplemented:               "not implemented",
	Internal:                     "internal error",
	Unavailable:                  "unavailable",
	InvalidArgument:              "invalid argument",
	OutOfRange:                   "out of range",
	InvalidRequest:               "invalid request",
	Unauthenticated:              "unauthenticated",
	PermissionDenied:             "permission denied",
	NotFound:                     "not found",
	AlreadyExists:                "already exists",
	Canceled:                     "canceled",
	DataLoss:                     "data loss",
	DataAccessFailed:             "data access failed",
	InvalidOperation:             "invalid operation",
	CustomizedExample:            "a customized example error",
	InvokeAlgorithmServerFailure: "failed to invoke algorithm server",
}
