// Code generated by go generate. DO NOT EDIT.

package errors

import (
	"errors"
)

var (
	// ErrUnknown [1000] 未知错误
	ErrUnknown = errors.New("[errcode:1000] unknown error")

	// ErrNotImplemented [1001] 方法未实现
	ErrNotImplemented = errors.New("[errcode:1001] not implemented")

	// ErrInternal [1002] 内部错误
	ErrInternal = errors.New("[errcode:1002] internal error")

	// ErrUnavailable [1003] 服务不可用
	ErrUnavailable = errors.New("[errcode:1003] unavailable")

	// ErrInvalidArgument [1004] 非法的参数
	ErrInvalidArgument = errors.New("[errcode:1004] invalid argument")

	// ErrOutOfRange [1005] 参数超出范围
	ErrOutOfRange = errors.New("[errcode:1005] out of range")

	// ErrInvalidRequest [1006] 非法的 Request 消息
	ErrInvalidRequest = errors.New("[errcode:1006] invalid request")

	// ErrUnauthenticated [1007] 未认证
	ErrUnauthenticated = errors.New("[errcode:1007] unauthenticated")

	// ErrPermissionDenied [1008] 拒绝访问
	ErrPermissionDenied = errors.New("[errcode:1008] permission denied")

	// ErrNotFound [1009] 资源未找到
	ErrNotFound = errors.New("[errcode:1009] not found")

	// ErrAlreadyExists [1010] 资源已存在
	ErrAlreadyExists = errors.New("[errcode:1010] already exists")

	// ErrCancelled [1011] 已取消
	ErrCancelled = errors.New("[errcode:1011] cancelled")

	// ErrDataLoss [1012] 数据丢失
	ErrDataLoss = errors.New("[errcode:1012] data loss")

	// ErrDataAccessFailed [1013] 数据访问失败
	ErrDataAccessFailed = errors.New("[errcode:1013] data access failed")

	// ErrInvalidOperation [1014] 非法的操作
	ErrInvalidOperation = errors.New("[errcode:1014] invalid operation")

	// ErrCustomizedError [9000] 自定义错误
	ErrCustomizedError = errors.New("[errcode:9000] customized error")
)
